### ISSUE TITLE
Copyright notice at top of each source file

### ISSUE THREAD

**Issue by mtazzari** [discsim/frankenstein#18]
Add this to the top of each source file

    Frankenstein: <DESC>
    Copyright (C) 2019-2020  R. Booth, J. Jennings, M. Tazzari

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <https://www.gnu.org/licenses/>.

where for <DESC> I suggest something like: `1D Fourier reconstruction algorithm with Gaussian Processes`

**Comment by rbooth200** [comment]
Fixed in #27
