### ISSUE TITLE
Fix __init__.py

### ISSUE THREAD

**Issue by rbooth200** [discsim/frankenstein#25]
We need to decide what belongs in __init__.py. Marco, can you take a look?

**Comment by mtazzari** [comment]
I think we don't need this line since we are not going to support Python v2 anymore:
`from __future__ import division, absolute_import, print_function`

I think on what we should/could add before closing the issue.

**Comment by mtazzari** [comment]
I'd make the changes in a PR, regardless how small it is, so we get it tested before merging into master.

**Comment by rbooth200** [comment]
Should we have any imports in there at all?

**Comment by jeffjennings** [comment]
I don't think they're needed for a couple reasons:
- I have all imports in fit.py
- It would be good to have an option to run the code in order to  just plot an existing fit

**Comment by rbooth200** [comment]
Ok, that's what I thought too. I'll remove all this stuff and leave an empty init file
