### ISSUE TITLE
change repo name to 'frank'

### ISSUE THREAD

**Issue by jeffjennings** [discsim/frankenstein#36]
Marco suggested waiting to do this until the repo is frozen.

Also change all internal 'frankenstein' mentions to 'frank'. 
NOTE: Only use find --> replace in the code itself (.py files), not anywhere else! The docs and other repo files mention the code as 'Frankenstein (frank)' ... don't want to overwrite those.

**Comment by rbooth200** [comment]
Fixed in #35
